FROM php:8.2-apache

# On copie vos fichiers dans le serveur
COPY . /var/www/html/

# On active les permissions pour que la base de données puisse s'écrire
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# On dit au serveur d'écouter sur le port 80
EXPOSE 80